name: Update Playlists

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:       # allow manual trigger

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Extract runf.py
        run: unzip -P ${{ secrets.ZIP_PASSWORD }} run.py

      - name: Run script
        run: python runf.py

      - name: Cleanup
        run: rm -f runf.py

      - name: Commit & Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add api.json ALL.m3u
          git commit -m "Auto update api.json and ALL.m3u" || echo "No changes"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
